<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Monthly Report — {{ $period['label'] }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { font-size: 20px; margin: 0 0 5px 0; }
        .header p { margin: 0; color: #666; }
        .section { margin-bottom: 20px; }
        .section h2 { font-size: 14px; border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th { background-color: #333; color: white; padding: 8px; text-align: left; font-size: 11px; }
        td { padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 11px; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .two-col { display: table; width: 100%; margin-bottom: 15px; }
        .col { display: table-cell; width: 50%; padding-right: 10px; vertical-align: top; }
        .stat-row { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #f0f0f0; }
        .footer { margin-top: 30px; text-align: center; color: #999; font-size: 10px; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Elevex — Monthly Report</h1>
        <p>{{ $period['label'] }} &nbsp;|&nbsp; {{ $period['start'] }} to {{ $period['end'] }}</p>
    </div>

    <div class="two-col">
        <div class="col">
            <div class="section">
                <h2>Tasks</h2>
                <div class="stat-row"><span>Total Created</span><strong>{{ $tasks['total'] }}</strong></div>
                <div class="stat-row"><span>Completed</span><strong>{{ $tasks['completed'] }}</strong></div>
                <div class="stat-row"><span>Overdue</span><strong>{{ $tasks['overdue'] }}</strong></div>
                <div class="stat-row"><span>Completion Rate</span><strong>{{ $tasks['completion_rate'] }}%</strong></div>
            </div>
        </div>
        <div class="col">
            <div class="section">
                <h2>Logbooks</h2>
                <div class="stat-row"><span>Total Submitted</span><strong>{{ $logbooks['total'] }}</strong></div>
                <div class="stat-row"><span>Approved</span><strong>{{ $logbooks['approved'] }}</strong></div>
                <div class="stat-row"><span>Approval Rate</span><strong>{{ $logbooks['approval_rate'] }}%</strong></div>
                <div class="stat-row"><span>Total Hours Logged</span><strong>{{ $logbooks['total_hours'] }}</strong></div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Top Performers</h2>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Intern</th>
                    <th>Overall Score</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                @forelse($top_performers as $index => $metric)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $metric->user->name ?? 'N/A' }}</td>
                    <td>{{ $metric->overall_score }}%</td>
                    <td>{{ $metric->grade() }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" style="text-align:center; color:#999;">No performance data available.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Intern Activity Breakdown</h2>
        <table>
            <thead>
                <tr>
                    <th>Intern</th>
                    <th>Tasks This Month</th>
                    <th>Logbooks This Month</th>
                    <th>Overall Score</th>
                </tr>
            </thead>
            <tbody>
                @forelse($interns as $intern)
                <tr>
                    <td>{{ $intern->name }}</td>
                    <td>{{ $intern->tasks_this_month ?? 0 }}</td>
                    <td>{{ $intern->logbooks_this_month ?? 0 }}</td>
                    <td>{{ $intern->performanceMetrics->first()?->overall_score ?? 'N/A' }}%</td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" style="text-align:center; color:#999;">No interns found.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by Elevex on {{ $generated_at }} &nbsp;|&nbsp; Confidential
    </div>
</body>
</html>