<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Weekly Report — {{ $period['label'] }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            margin: 0 0 5px 0;
        }
        .header p {
            margin: 0;
            color: #666;
        }
        .section {
            margin-bottom: 20px;
        }
        .section h2 {
            font-size: 14px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th {
            background-color: #333;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #eee;
            font-size: 11px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .stat-grid {
            display: table;
            width: 100%;
        }
        .stat-box {
            display: table-cell;
            text-align: center;
            padding: 10px;
            border: 1px solid #ddd;
            width: 16%;
        }
        .stat-value {
            font-size: 20px;
            font-weight: bold;
            color: #333;
        }
        .stat-label {
            font-size: 10px;
            color: #666;
            margin-top: 4px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #999;
            font-size: 10px;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Elevex — Weekly Report</h1>
        <p>{{ $period['label'] }} &nbsp;|&nbsp; {{ $period['start'] }} to {{ $period['end'] }}</p>
    </div>

    <div class="section">
        <h2>Summary</h2>
        <div class="stat-grid">
            <div class="stat-box">
                <div class="stat-value">{{ $summary['total_tasks'] }}</div>
                <div class="stat-label">Tasks Created</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $summary['completed_tasks'] }}</div>
                <div class="stat-label">Tasks Completed</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $summary['overdue_tasks'] }}</div>
                <div class="stat-label">Tasks Overdue</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $summary['total_logbooks'] }}</div>
                <div class="stat-label">Logbooks Submitted</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $summary['approved_logbooks'] }}</div>
                <div class="stat-label">Logbooks Approved</div>
            </div>
            <div class="stat-box">
                <div class="stat-value">{{ $summary['total_hours'] }}</div>
                <div class="stat-label">Hours Logged</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Intern Activity</h2>
        <table>
            <thead>
                <tr>
                    <th>Intern Name</th>
                    <th>Email</th>
                    <th>Tasks This Week</th>
                    <th>Logbooks This Week</th>
                </tr>
            </thead>
            <tbody>
                @forelse($interns as $intern)
                <tr>
                    <td>{{ $intern->name }}</td>
                    <td>{{ $intern->email }}</td>
                    <td>{{ $intern->tasks_this_week ?? 0 }}</td>
                    <td>{{ $intern->logbooks_this_week ?? 0 }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" style="text-align:center; color:#999;">No intern activity this week.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by Elevex on {{ $generated_at }} &nbsp;|&nbsp; Confidential
    </div>
</body>
</html>