<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;

/**
 * ActivityLog Model
 *
 * An immutable audit trail of everything that happens in Elevex.
 * Every significant action is recorded here automatically via
 * the WriteActivityLog listener which fires on domain events.
 *
 * Immutable means:
 *   Rows are NEVER updated — no updated_at column
 *   Rows are NEVER deleted — no SoftDeletes
 *   Once written, a log entry is permanent
 *
 * This table answers audit questions like:
 *   "Who approved this logbook and when?"
 *   "When was this task first assigned?"
 *   "How many times did this intern log in this month?"
 *   "What changed on this project and who changed it?"
 *
 * Event naming convention we follow:
 *   'auth.login'               — user logged in
 *   'auth.logout'              — user logged out
 *   'project.created'          — project was created
 *   'project.updated'          — project was updated
 *   'task.assigned'            — task assigned to intern
 *   'task.completed'           — intern completed a task
 *   'logbook.submitted'        — intern submitted logbook
 *   'logbook.approved'         — admin approved logbook
 *   'logbook.rejected'         — admin rejected logbook
 *   'evaluation.submitted'     — admin submitted evaluation
 *   'recommendation.generated' — recommendation letter generated
 *
 * Polymorphic subject:
 *   Points to whatever was acted on.
 *   e.g. a Task, Logbook, Project, User etc.
 *   Nullable because some events have no specific resource.
 *   e.g. 'auth.login' has no subject.
 *
 * metadata:
 *   JSON column for extra context.
 *   e.g. { "old_status": "submitted", "new_status": "approved" }
 *   Useful for displaying "what changed" in activity feeds.
 *
 * Note: No HasFactory trait — we never fake audit logs in tests.
 * Activity logs are always generated by real application events.
 *
 * Relationships:
 *   user    — who performed this action
 *   subject — what was acted on (polymorphic, nullable)
 */
class ActivityLog extends Model
{
    /**
     * No updated_at column — logs are immutable.
     * We tell Laravel to only manage created_at.
     */
    const UPDATED_AT = null;

    protected $fillable = [
        'user_id',
        'event',
        'description',
        'subject_id',
        'subject_type',
        'metadata',
        'ip_address',
    ];

    protected function casts(): array
    {
        return [
            // metadata stored as JSON, automatically converted
            // to a PHP array when accessed
            'metadata'   => 'array',
            'created_at' => 'datetime',
        ];
    }

    // =========================================================
    // Relationships
    // =========================================================

    /**
     * The user who performed this action.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * The model this action was performed on.
     * Could be a Task, Logbook, Project, User etc.
     * Null for events with no specific resource e.g. auth.login
     *
     * MorphTo looks at subject_type to know which model to load
     * then uses subject_id to find the specific record.
     */
    public function subject(): MorphTo
    {
        return $this->morphTo();
    }
}