<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Support\Facades\Storage;

/**
 * FileUpload Model
 *
 * Stores metadata about every file uploaded in the system.
 * The actual file lives on disk — in storage/app/public locally
 * or on S3 in production.
 *
 * We NEVER store file contents in the database.
 * We store the path and let Laravel's Storage facade serve the file.
 *
 * Polymorphic relationship:
 *   Files can be attached to different models:
 *     Logbook — proof of work uploads
 *     User    — profile picture / avatar
 *
 * disk column:
 *   'public' — local storage (development)
 *   's3'     — Amazon S3 (production)
 *   This design means switching to S3 is a config change,
 *   not a code change. The model handles both transparently.
 *
 * Security:
 *   stored_name is a UUID generated by FileUploadService.
 *   This prevents users from guessing other files' paths
 *   and prevents filename conflicts.
 *
 * Relationships:
 *   user       — who uploaded this file
 *   uploadable — the model this file is attached to
 */
class FileUpload extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'uploadable_id',
        'uploadable_type',
        'original_name',
        'stored_name',
        'path',
        'mime_type',
        'size',
        'disk',
    ];

    protected function casts(): array
    {
        return [
            // size stored as integer bytes
            // access via $file->size returns an integer
            'size' => 'integer',
        ];
    }

    // =========================================================
    // Helper Methods
    // =========================================================

    /**
     * Get the full public URL to this file.
     *
     * Storage::disk($this->disk)->url($this->path) handles both
     * local and S3 storage transparently — the URL format differs
     * but the code calling it never needs to know which disk is used.
     *
     * Usage:
     *   $file->url — returns the full accessible URL
     */
    public function getUrlAttribute(): string
    {
        return Storage::disk($this->disk)->url($this->path);
    }

    /**
     * Get the file size in a human readable format.
     * Converts bytes to KB, MB etc.
     *
     * Usage:
     *   $file->human_size — returns "2.4 MB"
     */
    public function getHumanSizeAttribute(): string
    {
        $bytes = $this->size;

        if ($bytes < 1024) {
            return $bytes . ' B';
        } elseif ($bytes < 1048576) {
            return round($bytes / 1024, 2) . ' KB';
        } else {
            return round($bytes / 1048576, 2) . ' MB';
        }
    }

    /**
     * Is this file an image?
     * Used to decide whether to show a preview in the UI.
     */
    public function isImage(): bool
    {
        return str_starts_with($this->mime_type, 'image/');
    }

    /**
     * Is this file a PDF?
     */
    public function isPdf(): bool
    {
        return $this->mime_type === 'application/pdf';
    }

    // =========================================================
    // Relationships
    // =========================================================

    /**
     * The user who uploaded this file.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * The model this file is attached to — Logbook or User.
     * MorphTo is the inverse of MorphMany.
     *
     * Usage:
     *   $file->uploadable — returns the Logbook or User this file belongs to
     */
    public function uploadable(): MorphTo
    {
        return $this->morphTo();
    }
}