<?php

namespace App\Services;

use App\Enums\RecommendationStatus;
use App\Enums\UserRole;
use App\Models\Internship;
use App\Models\RecommendationLetter;
use App\Models\User;
use App\Notifications\RecommendationStatusChanged;
use App\Services\Reports\Builders\PerformanceReportBuilder;
use App\Services\Reports\Exports\PdfExporter;
use Illuminate\Validation\ValidationException;

/**
 * RecommendationService
 *
 * Flow:
 *   1. Intern requests OR admin generates for an intern
 *   2. System builds a draft letter body from performance metrics
 *   3. Admin edits the draft (add / remove / rewrite)
 *   4. Admin approves → PDF generated from the edited body
 *      OR rejects the request
 */
class RecommendationService
{
    public function __construct(
        private readonly PerformanceReportBuilder $performanceBuilder,
        private readonly PdfExporter              $pdfExporter
    ) {}

    /**
     * Intern requests a recommendation letter.
     * Creates a pending (draft) record and auto-fills the body.
     */
    public function requestLetter(User $intern, int $internshipId): RecommendationLetter
    {
        $exists = RecommendationLetter::where('user_id', $intern->id)
            ->where('internship_id', $internshipId)
            ->exists();

        if ($exists) {
            throw ValidationException::withMessages([
                'internship_id' => ['A recommendation letter has already been requested for this internship.'],
            ]);
        }

        $internship = $intern->internships()->findOrFail($internshipId);

        $letter = RecommendationLetter::create([
            'user_id'       => $intern->id,
            'internship_id' => $internship->id,
            'status'        => RecommendationStatus::Pending,
            'body'          => $this->buildDraftBody($intern, $internship),
        ]);

        return $letter->load(['user', 'internship', 'approvedBy']);
    }

    /**
     * Admin generates a draft letter for a specific intern (no intern request needed).
     */
    public function generateForIntern(int $userId, User $admin): RecommendationLetter
    {
        $intern = User::where('role', UserRole::Intern)->findOrFail($userId);

        $internship = $intern->activeInternship;
        if (!$internship) {
            throw ValidationException::withMessages([
                'user_id' => ['This intern has no active internship.'],
            ]);
        }

        $exists = RecommendationLetter::where('user_id', $intern->id)
            ->where('internship_id', $internship->id)
            ->whereIn('status', [
                RecommendationStatus::Pending->value,
                RecommendationStatus::Approved->value,
            ])
            ->exists();

        if ($exists) {
            throw ValidationException::withMessages([
                'user_id' => ['A draft or approved letter already exists for this intern\'s internship.'],
            ]);
        }

        $letter = RecommendationLetter::create([
            'user_id'       => $intern->id,
            'internship_id' => $internship->id,
            'status'        => RecommendationStatus::Pending,
            'body'          => $this->buildDraftBody($intern, $internship),
            'admin_notes'   => 'Generated by ' . $admin->name,
        ]);

        return $letter->load(['user', 'internship', 'approvedBy']);
    }

    /**
     * Rebuild the draft body from current performance data.
     * Only allowed while the letter is still a draft (pending).
     */
    public function regenerateDraft(int $letterId): RecommendationLetter
    {
        $letter = RecommendationLetter::with(['user', 'internship'])->findOrFail($letterId);

        if (!$letter->isPending()) {
            throw ValidationException::withMessages([
                'status' => ['Only draft letters can be regenerated.'],
            ]);
        }

        $letter->update([
            'body' => $this->buildDraftBody($letter->user, $letter->internship),
        ]);

        return $letter->fresh(['user', 'internship', 'approvedBy']);
    }

    /**
     * Admin updates the editable draft body.
     */
    public function updateDraft(int $letterId, string $body): RecommendationLetter
    {
        $letter = RecommendationLetter::findOrFail($letterId);

        if (!$letter->isPending()) {
            throw ValidationException::withMessages([
                'status' => ['Only draft letters can be edited.'],
            ]);
        }

        $letter->update(['body' => $body]);

        return $letter->fresh(['user', 'internship', 'approvedBy']);
    }

    /**
     * Approve draft → lock content into a PDF for the intern to download.
     */
    public function approveLetter(int $letterId, User $admin): RecommendationLetter
    {
        $letter = RecommendationLetter::with(['user', 'internship'])->findOrFail($letterId);

        if (!$letter->isPending()) {
            throw ValidationException::withMessages([
                'status' => ['Only draft letters can be approved.'],
            ]);
        }

        if (!filled($letter->body)) {
            $letter->body = $this->buildDraftBody($letter->user, $letter->internship);
            $letter->save();
        }

        $pdfPath = $this->pdfExporter->generate(
            view: 'pdfs.recommendation',
            data: [
                'intern'     => $letter->user,
                'internship' => $letter->internship,
                'admin'      => $admin,
                'letter'     => $letter,
                'body'       => $letter->body,
            ],
            folder: 'letters'
        );

        $letter->update([
            'status'       => RecommendationStatus::Approved,
            'approved_by'  => $admin->id,
            'approved_at'  => now(),
            'generated_at' => now(),
            'pdf_path'     => $pdfPath,
        ]);

        $letter = $letter->fresh(['user', 'internship', 'approvedBy']);
        $letter->user->notify(new RecommendationStatusChanged($letter, 'approved'));

        return $letter;
    }

    public function rejectLetter(int $letterId, User $admin, ?string $notes = null): RecommendationLetter
    {
        $letter = RecommendationLetter::with('user')->findOrFail($letterId);

        if (!$letter->isPending()) {
            throw ValidationException::withMessages([
                'status' => ['Only draft letters can be rejected.'],
            ]);
        }

        $letter->update([
            'status'      => RecommendationStatus::Rejected,
            'approved_by' => $admin->id,
            'admin_notes' => $notes,
        ]);

        $letter = $letter->fresh(['user', 'internship', 'approvedBy']);
        $letter->user->notify(new RecommendationStatusChanged($letter, 'rejected'));

        return $letter;
    }

    public function getAllLetters(array $filters = [], ?User $scopeToUser = null)
    {
        return RecommendationLetter::with(['user', 'internship', 'approvedBy'])
            ->when($scopeToUser, fn ($q) => $q->where('user_id', $scopeToUser->id))
            ->when(isset($filters['status']), fn ($q) => $q->where('status', $filters['status']))
            ->latest()
            ->get();
    }

    public function getLetterById(int $id): RecommendationLetter
    {
        return RecommendationLetter::with(['user', 'internship', 'approvedBy'])
            ->findOrFail($id);
    }

    /**
     * Build plain-text draft from live performance / achievements / skills.
     */
    public function buildDraftBody(User $intern, Internship $internship): string
    {
        $performance = $this->performanceBuilder->build($intern);
        $achievements = $this->translateAchievements($performance['achievements']);
        $metric = $performance['metric'];
        $grade = $performance['grade'];

        $start = $internship->start_date->format('F d, Y');
        $end = $internship->end_date->format('F d, Y');
        $days = $internship->durationInDays();
        $department = $internship->department;

        $paragraphs = [];

        $paragraphs[] = 'To Whom It May Concern,';

        $paragraphs[] = "It is with great pleasure that I write this letter of recommendation for {$intern->name}, "
            . "who completed an internship with our organization from {$start} to {$end} "
            . "in the {$department} department.";

        $paragraphs[] = "Throughout the internship period of {$days} days, {$intern->name} demonstrated "
            . 'consistent professionalism and dedication to their assigned responsibilities.';

        if ($metric) {
            $paragraphs[] = 'Performance summary: '
                . "overall score {$metric->overall_score}% ({$grade}), "
                . "task completion {$metric->completion_rate}%, "
                . "deadline adherence {$metric->deadline_score}%, "
                . "and consistency {$metric->consistency_score}%.";
        }

        if (count($achievements) > 0) {
            $phrases = collect($achievements)->pluck('professional_phrase')->implode('; ');
            $paragraphs[] = "During their time with us, {$intern->name} {$phrases}.";
        }

        $skills = $performance['skills'] ?? collect();
        if ($skills->count() > 0) {
            $skillNames = $skills->pluck('name')->implode(', ');
            $paragraphs[] = "{$intern->name} demonstrated proficiency in the following areas: {$skillNames}.";
        }

        $paragraphs[] = "Based on their performance, work ethic, and the quality of contributions "
            . "made during this internship, I have no hesitation in recommending {$intern->name} "
            . 'for future opportunities. They would be a valuable asset to any organization.';

        $paragraphs[] = 'Please feel free to reach out should you require any further information.';

        $paragraphs[] = "Sincerely,\n[Supervisor name will appear on the signed PDF]";

        return implode("\n\n", $paragraphs);
    }

    private function translateAchievements(\Illuminate\Support\Collection $achievements): array
    {
        $translations = [
            'perfect_attendance'   => 'demonstrated exceptional attendance and commitment throughout the internship period',
            'fast_finisher'        => 'consistently delivered work ahead of schedule, demonstrating strong time management skills',
            'thirty_day_streak'    => 'maintained consistent daily documentation over an extended period',
            'team_player'          => 'contributed meaningfully across multiple projects simultaneously',
            'top_performer'        => 'achieved outstanding overall performance scores across all evaluation dimensions',
            'milestone_master'     => 'consistently completed project milestones ahead of schedule',
            'consistency_champion' => 'maintained exceptional consistency in work documentation throughout the internship',
        ];

        return $achievements->map(function ($achievement) use ($translations) {
            return [
                'key'                 => $achievement->key,
                'name'                => $achievement->name,
                'professional_phrase' => $translations[$achievement->key]
                    ?? $achievement->description,
            ];
        })->toArray();
    }
}
