<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Recommendation Letter — {{ $intern->name }}</title>
    <style>
        body { font-family: Georgia, serif; font-size: 12px; color: #333; margin: 0; padding: 40px; line-height: 1.7; }
        .header { margin-bottom: 40px; }
        .company-name { font-size: 20px; font-weight: bold; color: #333; }
        .company-sub { font-size: 11px; color: #666; margin-top: 3px; }
        .date { margin: 30px 0; }
        .subject { margin-bottom: 25px; }
        .subject strong { font-size: 13px; }
        .body p { margin-bottom: 15px; text-align: justify; white-space: pre-wrap; }
        .signature { margin-top: 40px; }
        .signature-name { font-weight: bold; margin-top: 50px; }
        .signature-title { color: #666; font-size: 11px; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 10px; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>

    <div class="header">
        <div class="company-name">Elevex</div>
        <div class="company-sub">Internship Management Platform</div>
    </div>

    <div class="date">{{ now()->format('F d, Y') }}</div>

    <div class="subject">
        <strong>RE: Letter of Recommendation — {{ $intern->name }}</strong>
    </div>

    <div class="body">
        @foreach(preg_split("/\n\s*\n/", trim($body)) as $paragraph)
            <p>{{ $paragraph }}</p>
        @endforeach
    </div>

    <div class="signature">
        <div class="signature-name">{{ $admin->name }}</div>
        <div class="signature-title">Supervisor, Elevex</div>
    </div>

    <div class="footer">
        This letter was generated by Elevex on {{ now()->format('F d, Y') }} &nbsp;|&nbsp; Confidential
    </div>

</body>
</html>
