<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Recommendation Letter — {{ $intern->name }}</title>
    <style>
        body { font-family: Georgia, serif; font-size: 12px; color: #333; margin: 0; padding: 40px; line-height: 1.7; }
        .header { margin-bottom: 40px; }
        .company-name { font-size: 20px; font-weight: bold; color: #333; }
        .company-sub { font-size: 11px; color: #666; margin-top: 3px; }
        .date { margin: 30px 0; }
        .subject { margin-bottom: 25px; }
        .subject strong { font-size: 13px; }
        .body p { margin-bottom: 15px; text-align: justify; }
        .signature { margin-top: 40px; }
        .signature-name { font-weight: bold; margin-top: 50px; }
        .signature-title { color: #666; font-size: 11px; }
        .performance-box { border: 1px solid #ccc; padding: 15px; margin: 20px 0; background-color: #f9f9f9; }
        .performance-box h3 { margin: 0 0 10px 0; font-size: 12px; }
        .perf-row { display: flex; justify-content: space-between; margin-bottom: 5px; font-size: 11px; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 10px; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>

    <div class="header">
        <div class="company-name">Elevex</div>
        <div class="company-sub">Internship Management Platform</div>
    </div>

    <div class="date">{{ now()->format('F d, Y') }}</div>

    <div class="subject">
        <strong>RE: Letter of Recommendation — {{ $intern->name }}</strong>
    </div>

    <div class="body">
        <p>To Whom It May Concern,</p>

        <p>
            It is with great pleasure that I write this letter of recommendation for
            <strong>{{ $intern->name }}</strong>, who completed an internship with our
            organization from
            <strong>{{ $internship->start_date->format('F d, Y') }}</strong> to
            <strong>{{ $internship->end_date->format('F d, Y') }}</strong>
            in the <strong>{{ $internship->department }}</strong> department.
        </p>

        <p>
            Throughout the internship period of {{ $internship->durationInDays() }} days,
            {{ $intern->name }} demonstrated consistent professionalism and dedication
            to their assigned responsibilities.
        </p>

        @if($performance['metric'])
        <div class="performance-box">
            <h3>Performance Summary</h3>
            <div class="perf-row">
                <span>Overall Performance Score</span>
                <strong>{{ $performance['metric']->overall_score }}% ({{ $performance['grade'] }})</strong>
            </div>
            <div class="perf-row">
                <span>Task Completion Rate</span>
                <strong>{{ $performance['metric']->completion_rate }}%</strong>
            </div>
            <div class="perf-row">
                <span>Deadline Adherence</span>
                <strong>{{ $performance['metric']->deadline_score }}%</strong>
            </div>
            <div class="perf-row">
                <span>Consistency Score</span>
                <strong>{{ $performance['metric']->consistency_score }}%</strong>
            </div>
        </div>
        @endif

        @if(count($performance['achievements']) > 0)
        <p>During their time with us, {{ $intern->name }}:</p>
        <ul>
            @foreach($performance['achievements'] as $achievement)
            <li>{{ $achievement['professional_phrase'] }}</li>
            @endforeach
        </ul>
        @endif

        @if(count($performance['skills']) > 0)
        <p>
            {{ $intern->name }} demonstrated proficiency in the following areas:
            {{ $performance['skills']->pluck('name')->implode(', ') }}.
        </p>
        @endif

        <p>
            Based on their performance, work ethic, and the quality of contributions
            made during this internship, I have no hesitation in recommending
            {{ $intern->name }} for future opportunities. They would be a valuable
            asset to any organization.
        </p>

        <p>
            Please feel free to reach out should you require any further information.
        </p>
    </div>

    <div class="signature">
        <p>Sincerely,</p>
        <div class="signature-name">{{ $admin->name }}</div>
        <div class="signature-title">Supervisor, Elevex</div>
    </div>

    <div class="footer">
        This letter was generated by Elevex on {{ now()->format('F d, Y') }} &nbsp;|&nbsp; Confidential
    </div>

</body>
</html>