<?php

namespace App\Http\Resources\V1;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * FileUploadResource
 *
 * Shapes the FileUpload model into a consistent API response.
 *
 * url: the full accessible URL to the file.
 *      Generated by FileUpload@getUrlAttribute.
 *      Works transparently for both local and S3 storage.
 *
 * human_size: e.g. "2.4 MB" instead of raw bytes.
 *             Generated by FileUpload@getHumanSizeAttribute.
 */
class FileUploadResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id'            => $this->id,
            'original_name' => $this->original_name,
            'url'           => $this->url,
            'mime_type'     => $this->mime_type,
            'size'          => $this->size,
            'human_size'    => $this->human_size,
            'is_image'      => $this->isImage(),
            'is_pdf'        => $this->isPdf(),
            'created_at'    => $this->created_at->toISOString(),
        ];
    }
}