<?php

namespace App\Http\Resources\V1;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * RecommendationLetterResource
 *
 * Shapes the RecommendationLetter model into a consistent API response.
 *
 * pdf_url: the full accessible URL to download the PDF.
 *   Only present when status is approved and PDF has been generated.
 *   Generated by RecommendationLetter@getPdfUrlAttribute.
 */
class RecommendationLetterResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id'           => $this->id,
            'status'       => $this->status->value,
            'status_label' => $this->status->label(),
            'pdf_url'      => $this->pdf_url,
            'generated_at' => $this->generated_at?->toISOString(),
            'approved_at'  => $this->approved_at?->toISOString(),
            'admin_notes'  => $this->admin_notes,
            'body'         => $this->body,

            // Only included when relationship is loaded
            'user'        => new UserResource($this->whenLoaded('user')),
            'internship'  => $this->whenLoaded('internship'),
            'approved_by' => new UserResource($this->whenLoaded('approvedBy')),

            'created_at'  => $this->created_at->toISOString(),
        ];
    }
}